<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" time="1.162" timestamp="2025-07-27T23:54:50.299" name="AllTests">
  <testsuite name="ComplexWorkflowChainsTest" tests="1" failures="1" disabled="0" skipped="0" errors="0" time="1.119" timestamp="2025-07-27T23:54:50.343">
    <testcase name="PerformanceStressWorkflow_RapidOperations" file="/home/bigattichouse/workspace/headlessweb/tests/integration/test_complex_workflow_chains.cpp" line="841" status="run" result="completed" time="1.119" timestamp="2025-07-27T23:54:50.343" classname="ComplexWorkflowChainsTest">
      <failure message="unknown file&#x0A;C++ exception with description &quot;stoi&quot; thrown in the test body.&#x0A;" type=""><![CDATA[unknown file
C++ exception with description "stoi" thrown in the test body.
]]></failure>
    </testcase>
  </testsuite>
</testsuites>
